// Generated by tools/pumpkin-import/import_protocol_ids.py. Do not edit.
// Pumpkin beb6947dfc21a1a781523bf207a3c2740f4928f9, Minecraft 26.2, protocol 776.

pub mod cb {
    pub const STATUS_RESPONSE: i32 = 0x00; // status.STATUS_RESPONSE
    pub const STATUS_PING: i32 = 0x01; // status.PONG_RESPONSE

    pub const LOGIN_DISCONNECT: i32 = 0x00; // login.LOGIN_DISCONNECT
    pub const LOGIN_SUCCESS: i32 = 0x02; // login.LOGIN_FINISHED
    pub const LOGIN_COMPRESS: i32 = 0x03; // login.LOGIN_COMPRESSION

    pub const CFG_CUSTOM_PAYLOAD: i32 = 0x01; // config.CUSTOM_PAYLOAD
    pub const CFG_DISCONNECT: i32 = 0x02; // config.DISCONNECT
    pub const CFG_FINISH: i32 = 0x03; // config.FINISH_CONFIGURATION
    pub const CFG_KEEP_ALIVE: i32 = 0x04; // config.KEEP_ALIVE
    pub const CFG_PING: i32 = 0x05; // config.PING
    pub const CFG_REGISTRY_DATA: i32 = 0x07; // config.REGISTRY_DATA
    pub const CFG_TAGS: i32 = 0x0d; // config.UPDATE_TAGS
    pub const CFG_KNOWN_PACKS: i32 = 0x0e; // config.SELECT_KNOWN_PACKS

    pub const PLAY_SPAWN_ENTITY: i32 = 0x01; // play.ADD_ENTITY
    pub const PLAY_ANIMATION: i32 = 0x02; // play.ANIMATE
    pub const PLAY_ACK_DIGGING: i32 = 0x04; // play.BLOCK_CHANGED_ACK
    pub const PLAY_BLOCK_CHANGE: i32 = 0x08; // play.BLOCK_UPDATE
    pub const PLAY_CHUNK_BATCH_FINISHED: i32 = 0x0b; // play.CHUNK_BATCH_FINISHED
    pub const PLAY_CHUNK_BATCH_START: i32 = 0x0c; // play.CHUNK_BATCH_START
    pub const PLAY_CUSTOM_PAYLOAD: i32 = 0x18; // play.CUSTOM_PAYLOAD
    pub const PLAY_DAMAGE_EVENT: i32 = 0x19; // play.DAMAGE_EVENT
    pub const PLAY_KICK_DISCONNECT: i32 = 0x20; // play.DISCONNECT
    pub const PLAY_SYNC_ENTITY_POSITION: i32 = 0x23; // play.ENTITY_POSITION_SYNC
    pub const PLAY_UNLOAD_CHUNK: i32 = 0x25; // play.FORGET_LEVEL_CHUNK
    pub const PLAY_GAME_EVENT: i32 = 0x26; // play.GAME_EVENT
    pub const PLAY_HURT_ANIMATION: i32 = 0x2a; // play.HURT_ANIMATION
    pub const PLAY_KEEP_ALIVE: i32 = 0x2c; // play.KEEP_ALIVE
    pub const PLAY_CHUNK_DATA: i32 = 0x2d; // play.LEVEL_CHUNK_WITH_LIGHT
    pub const PLAY_LOGIN: i32 = 0x31; // play.LOGIN
    pub const PLAY_REL_ENTITY_MOVE: i32 = 0x35; // play.MOVE_ENTITY_POS
    pub const PLAY_ENTITY_MOVE_LOOK: i32 = 0x36; // play.MOVE_ENTITY_POS_ROT
    pub const PLAY_ENTITY_LOOK: i32 = 0x38; // play.MOVE_ENTITY_ROT
    pub const PLAY_PING_RESPONSE: i32 = 0x3e; // play.PONG_RESPONSE
    pub const PLAY_ABILITIES: i32 = 0x40; // play.PLAYER_ABILITIES
    pub const PLAY_PLAYER_REMOVE: i32 = 0x45; // play.PLAYER_INFO_REMOVE
    pub const PLAY_PLAYER_INFO: i32 = 0x46; // play.PLAYER_INFO_UPDATE
    pub const PLAY_POSITION: i32 = 0x48; // play.PLAYER_POSITION
    pub const PLAY_ENTITY_DESTROY: i32 = 0x4d; // play.REMOVE_ENTITIES
    pub const PLAY_ENTITY_HEAD_ROTATION: i32 = 0x53; // play.ROTATE_HEAD
    pub const PLAY_SPAWN_POSITION: i32 = 0x61; // play.SET_DEFAULT_SPAWN_POSITION
    pub const PLAY_SET_ENTITY_MOTION: i32 = 0x65; // play.SET_ENTITY_MOTION
    pub const PLAY_SET_HEALTH: i32 = 0x68; // play.SET_HEALTH
    pub const PLAY_SET_CHUNK_CACHE_CENTER: i32 = 0x5e; // play.SET_CHUNK_CACHE_CENTER
    pub const PLAY_UPDATE_TIME: i32 = 0x71; // play.SET_TIME
    pub const PLAY_SYSTEM_CHAT: i32 = 0x79; // play.SYSTEM_CHAT
    pub const PLAY_ENTITY_TELEPORT: i32 = 0x7d; // play.TELEPORT_ENTITY
}

pub mod sb {
    pub const HANDSHAKE: i32 = 0x00; // handshake.INTENTION

    pub const STATUS_REQUEST: i32 = 0x00; // status.STATUS_REQUEST
    pub const STATUS_PING: i32 = 0x01; // status.PING_REQUEST

    pub const LOGIN_START: i32 = 0x00; // login.HELLO
    pub const LOGIN_ACKNOWLEDGED: i32 = 0x03; // login.LOGIN_ACKNOWLEDGED

    pub const CFG_SETTINGS: i32 = 0x00; // config.CLIENT_INFORMATION
    pub const CFG_CUSTOM_PAYLOAD: i32 = 0x02; // config.CUSTOM_PAYLOAD
    pub const CFG_FINISH: i32 = 0x03; // config.FINISH_CONFIGURATION
    pub const CFG_KEEP_ALIVE: i32 = 0x04; // config.KEEP_ALIVE
    pub const CFG_PONG: i32 = 0x05; // config.PONG
    pub const CFG_KNOWN_PACKS: i32 = 0x07; // config.SELECT_KNOWN_PACKS

    pub const PLAY_TELEPORT_CONFIRM: i32 = 0x00; // play.ACCEPT_TELEPORTATION
    pub const PLAY_ATTACK: i32 = 0x01; // play.ATTACK
    pub const PLAY_CHAT_MESSAGE: i32 = 0x09; // play.CHAT
    pub const PLAY_CHUNK_BATCH_RECEIVED: i32 = 0x0b; // play.CHUNK_BATCH_RECEIVED
    pub const PLAY_SETTINGS: i32 = 0x0e; // play.CLIENT_INFORMATION
    pub const PLAY_CUSTOM_PAYLOAD: i32 = 0x16; // play.CUSTOM_PAYLOAD
    pub const PLAY_KEEP_ALIVE: i32 = 0x1c; // play.KEEP_ALIVE
    pub const PLAY_POSITION: i32 = 0x1e; // play.MOVE_PLAYER_POS
    pub const PLAY_POSITION_LOOK: i32 = 0x1f; // play.MOVE_PLAYER_POS_ROT
    pub const PLAY_LOOK: i32 = 0x20; // play.MOVE_PLAYER_ROT
    pub const PLAY_FLYING: i32 = 0x21; // play.MOVE_PLAYER_STATUS_ONLY
    pub const PLAY_PING_REQUEST: i32 = 0x26; // play.PING_REQUEST
    pub const PLAY_BLOCK_DIG: i32 = 0x29; // play.PLAYER_ACTION
    pub const PLAY_PONG: i32 = 0x2d; // play.PONG
    pub const PLAY_HELD_ITEM_SLOT: i32 = 0x35; // play.SET_CARRIED_ITEM
    pub const PLAY_SET_CREATIVE_SLOT: i32 = 0x38; // play.SET_CREATIVE_MODE_SLOT
    pub const PLAY_ARM_ANIMATION: i32 = 0x3f; // play.SWING
    pub const PLAY_BLOCK_PLACE: i32 = 0x42; // play.USE_ITEM_ON
    pub const PLAY_USE_ITEM: i32 = 0x43; // play.USE_ITEM
}
