#!/usr/bin/env python3
"""Import Minecraft 26.2 synchronized registries from pinned Pumpkin."""

import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path


PUMPKIN_REVISION = "beb6947dfc21a1a781523bf207a3c2740f4928f9"
PUMPKIN_VERSION = "0.1.0-dev+26.2-26.40"
REGISTRY_MARKER = "pub static REGISTRY_V_26_2"


def checked_revision(pumpkin: Path) -> str:
    revision = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=pumpkin, check=True, capture_output=True, text=True
    ).stdout.strip()
    if revision != PUMPKIN_REVISION:
        raise SystemExit(
            f"expected Pumpkin {PUMPKIN_REVISION}, found {revision}; refusing an unpinned import"
        )
    return revision


def decode_rust_byte_string(value: str) -> bytes:
    output = bytearray()
    index = 0
    escapes = {"0": 0, "n": 10, "r": 13, "t": 9, "\\": 92, '"': 34}
    while index < len(value):
        char = value[index]
        if char != "\\":
            encoded = char.encode("utf-8")
            output.extend(encoded)
            index += 1
            continue
        index += 1
        if index >= len(value):
            raise ValueError("trailing escape in Rust byte string")
        escape = value[index]
        if escape == "x":
            if index + 2 >= len(value):
                raise ValueError("truncated hexadecimal byte escape")
            output.append(int(value[index + 1 : index + 3], 16))
            index += 3
        elif escape in escapes:
            output.append(escapes[escape])
            index += 1
        else:
            raise ValueError(f"unsupported Rust byte escape: \\{escape}")
    return bytes(output)


def parse_v26_2(source: str) -> list[tuple[str, list[tuple[str, bytes]]]]:
    start = source.index(REGISTRY_MARKER)
    end = source.index("impl Registry", start)
    section = source[start:end]
    registry_matches = list(
        re.finditer(r'StaticRegistry \{ registry_id : "([^"]+)" , entries : & \[', section)
    )
    entry_pattern = re.compile(
        r'StaticRegistryEntry \{ name : "([^"]+)" , data : b"((?:\\.|[^"\\])*)" \}',
        re.DOTALL,
    )
    registries = []
    for index, registry_match in enumerate(registry_matches):
        segment_end = (
            registry_matches[index + 1].start() if index + 1 < len(registry_matches) else len(section)
        )
        segment = section[registry_match.end() : segment_end]
        entries = [
            (entry.group(1), decode_rust_byte_string(entry.group(2)))
            for entry in entry_pattern.finditer(segment)
        ]
        if not entries:
            raise SystemExit(f"no entries parsed for registry {registry_match.group(1)}")
        registries.append((registry_match.group(1), entries))
    if len(registries) != 29:
        raise SystemExit(f"expected 29 Pumpkin 26.2 registries, parsed {len(registries)}")
    return registries


def registry_index(
    registries: list[tuple[str, list[tuple[str, bytes]]]], registry: str, entry: str
) -> int:
    entries = dict(registries)[registry]
    return next(index for index, (name, _) in enumerate(entries) if name == entry)


def generate_rust(
    registries: list[tuple[str, list[tuple[str, bytes]]]], offsets: dict[tuple[str, str], tuple[int, int]]
) -> str:
    constants = {
        "BIOME_PLAINS": registry_index(registries, "worldgen/biome", "plains"),
        "DIMENSION_TYPE_OVERWORLD": registry_index(registries, "dimension_type", "overworld"),
        "DAMAGE_TYPE_PLAYER_ATTACK": registry_index(registries, "damage_type", "player_attack"),
        "WORLD_CLOCK_OVERWORLD": registry_index(registries, "world_clock", "overworld"),
    }
    lines = [
        "// Generated by tools/pumpkin-import/import_registries.py. Do not edit.",
        f"// Pumpkin {PUMPKIN_REVISION}, Minecraft 26.2.",
        "",
        "pub struct VanillaEntry {",
        "    pub name: &'static str,",
        "    pub offset: usize,",
        "    pub len: usize,",
        "}",
        "",
        "pub struct VanillaRegistry {",
        "    pub id: &'static str,",
        "    pub entries: &'static [VanillaEntry],",
        "}",
        "",
        'pub const REGISTRY_BLOB: &[u8] = include_bytes!("vanilla_registries.bin");',
        "",
    ]
    lines.extend(f"pub const {name}: i32 = {value};" for name, value in constants.items())
    lines.extend(["", "pub static VANILLA_REGISTRIES: &[VanillaRegistry] = &["])
    for registry, entries in registries:
        lines.extend(
            [
                "    VanillaRegistry {",
                f'        id: "minecraft:{registry}",',
                "        entries: &[",
            ]
        )
        for entry, _ in entries:
            offset, length = offsets[(registry, entry)]
            lines.append(
                f'            VanillaEntry {{ name: "{entry}", offset: {offset}, len: {length} }},'
            )
        lines.extend(["        ],", "    },"])
    lines.extend(
        [
            "];",
            "",
            "#[cfg(test)]",
            "mod tests {",
            "    use super::*;",
            "",
            "    fn entry_index(registry: &str, entry: &str) -> i32 {",
            "        let registry = VANILLA_REGISTRIES.iter().find(|value| value.id == registry).unwrap();",
            "        registry.entries.iter().position(|value| value.name == entry).unwrap() as i32",
            "    }",
            "",
            "    #[test]",
            "    fn pumpkin_26_2_registry_blob_is_complete() {",
            "        assert_eq!(VANILLA_REGISTRIES.len(), 29);",
            "        assert_eq!(VANILLA_REGISTRIES.iter().map(|value| value.entries.len()).sum::<usize>(), 398);",
            "        for registry in VANILLA_REGISTRIES {",
            "            for entry in registry.entries {",
            "                let data = REGISTRY_BLOB.get(entry.offset..entry.offset + entry.len).unwrap();",
            "                assert_eq!(data.first(), Some(&0x0a), \"{}.{}\", registry.id, entry.name);",
            "            }",
            "        }",
            "    }",
            "",
            "    #[test]",
            "    fn generated_wire_indices_match_registry_order() {",
            '        assert_eq!(BIOME_PLAINS, entry_index("minecraft:worldgen/biome", "plains"));',
            '        assert_eq!(DIMENSION_TYPE_OVERWORLD, entry_index("minecraft:dimension_type", "overworld"));',
            '        assert_eq!(DAMAGE_TYPE_PLAYER_ATTACK, entry_index("minecraft:damage_type", "player_attack"));',
            '        assert_eq!(WORLD_CLOCK_OVERWORLD, entry_index("minecraft:world_clock", "overworld"));',
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("pumpkin", type=Path, help="path to the pinned Pumpkin checkout")
    parser.add_argument(
        "--rust-output",
        type=Path,
        default=Path("crates/server-do/src/vanilla_registries.rs"),
    )
    parser.add_argument(
        "--blob-output",
        type=Path,
        default=Path("crates/server-do/src/vanilla_registries.bin"),
    )
    parser.add_argument(
        "--manifest-output",
        type=Path,
        default=Path("crates/server-do/registry-26.2-manifest.json"),
    )
    args = parser.parse_args()

    pumpkin = args.pumpkin.resolve()
    revision = checked_revision(pumpkin)
    source_path = pumpkin / "crates" / "pumpkin-data" / "src" / "generated" / "registry.rs"
    source_bytes = source_path.read_bytes()
    registries = parse_v26_2(source_bytes.decode())

    blob = bytearray()
    offsets = {}
    for registry, entries in registries:
        for entry, data in entries:
            offsets[(registry, entry)] = (len(blob), len(data))
            blob.extend(data)

    args.rust_output.parent.mkdir(parents=True, exist_ok=True)
    args.rust_output.write_text(generate_rust(registries, offsets))
    args.blob_output.parent.mkdir(parents=True, exist_ok=True)
    args.blob_output.write_bytes(blob)

    notable_indices = {
        "minecraft:worldgen/biome/minecraft:plains": registry_index(
            registries, "worldgen/biome", "plains"
        ),
        "minecraft:dimension_type/minecraft:overworld": registry_index(
            registries, "dimension_type", "overworld"
        ),
        "minecraft:damage_type/minecraft:player_attack": registry_index(
            registries, "damage_type", "player_attack"
        ),
        "minecraft:world_clock/minecraft:overworld": registry_index(
            registries, "world_clock", "overworld"
        ),
    }
    manifest = {
        "format": 1,
        "minecraft_version": "26.2",
        "pumpkin_revision": revision,
        "pumpkin_version": PUMPKIN_VERSION,
        "source": "crates/pumpkin-data/src/generated/registry.rs",
        "source_sha256": hashlib.sha256(source_bytes).hexdigest(),
        "blob_sha256": hashlib.sha256(blob).hexdigest(),
        "blob_size": len(blob),
        "registry_count": len(registries),
        "registries": [
            {"id": f"minecraft:{registry}", "entry_count": len(entries)}
            for registry, entries in registries
        ],
        "notable_indices": notable_indices,
    }
    args.manifest_output.parent.mkdir(parents=True, exist_ok=True)
    args.manifest_output.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")


if __name__ == "__main__":
    main()
