// Generated by tools/pumpkin-import/import_registries.py. Do not edit.
// Pumpkin beb6947dfc21a1a781523bf207a3c2740f4928f9, Minecraft 26.2.

pub struct VanillaEntry {
    pub name: &'static str,
    pub offset: usize,
    pub len: usize,
}

pub struct VanillaRegistry {
    pub id: &'static str,
    pub entries: &'static [VanillaEntry],
}

pub const REGISTRY_BLOB: &[u8] = include_bytes!("vanilla_registries.bin");

pub const BIOME_PLAINS: i32 = 40;
pub const DIMENSION_TYPE_OVERWORLD: i32 = 0;
pub const DAMAGE_TYPE_PLAYER_ATTACK: i32 = 34;
pub const WORLD_CLOCK_OVERWORLD: i32 = 0;

pub static VANILLA_REGISTRIES: &[VanillaRegistry] = &[
    VanillaRegistry {
        id: "minecraft:worldgen/biome",
        entries: &[
            VanillaEntry {
                name: "badlands",
                offset: 0,
                len: 3089,
            },
            VanillaEntry {
                name: "bamboo_jungle",
                offset: 3089,
                len: 3186,
            },
            VanillaEntry {
                name: "basalt_deltas",
                offset: 6275,
                len: 1628,
            },
            VanillaEntry {
                name: "beach",
                offset: 7903,
                len: 2454,
            },
            VanillaEntry {
                name: "birch_forest",
                offset: 10357,
                len: 2881,
            },
            VanillaEntry {
                name: "cherry_grove",
                offset: 13238,
                len: 2746,
            },
            VanillaEntry {
                name: "cold_ocean",
                offset: 15984,
                len: 3068,
            },
            VanillaEntry {
                name: "crimson_forest",
                offset: 19052,
                len: 1719,
            },
            VanillaEntry {
                name: "dark_forest",
                offset: 20771,
                len: 2928,
            },
            VanillaEntry {
                name: "deep_cold_ocean",
                offset: 23699,
                len: 3073,
            },
            VanillaEntry {
                name: "deep_dark",
                offset: 26772,
                len: 1733,
            },
            VanillaEntry {
                name: "deep_frozen_ocean",
                offset: 28505,
                len: 2860,
            },
            VanillaEntry {
                name: "deep_lukewarm_ocean",
                offset: 31365,
                len: 3267,
            },
            VanillaEntry {
                name: "deep_ocean",
                offset: 34632,
                len: 3069,
            },
            VanillaEntry {
                name: "desert",
                offset: 37701,
                len: 2950,
            },
            VanillaEntry {
                name: "dripstone_caves",
                offset: 40651,
                len: 2657,
            },
            VanillaEntry {
                name: "end_barrens",
                offset: 43308,
                len: 378,
            },
            VanillaEntry {
                name: "end_highlands",
                offset: 43686,
                len: 482,
            },
            VanillaEntry {
                name: "end_midlands",
                offset: 44168,
                len: 378,
            },
            VanillaEntry {
                name: "eroded_badlands",
                offset: 44546,
                len: 3089,
            },
            VanillaEntry {
                name: "flower_forest",
                offset: 47635,
                len: 2922,
            },
            VanillaEntry {
                name: "forest",
                offset: 50557,
                len: 2932,
            },
            VanillaEntry {
                name: "frozen_ocean",
                offset: 53489,
                len: 2860,
            },
            VanillaEntry {
                name: "frozen_peaks",
                offset: 56349,
                len: 2485,
            },
            VanillaEntry {
                name: "frozen_river",
                offset: 58834,
                len: 2907,
            },
            VanillaEntry {
                name: "grove",
                offset: 61741,
                len: 2616,
            },
            VanillaEntry {
                name: "ice_spikes",
                offset: 64357,
                len: 2697,
            },
            VanillaEntry {
                name: "jagged_peaks",
                offset: 67054,
                len: 2485,
            },
            VanillaEntry {
                name: "jungle",
                offset: 69539,
                len: 3180,
            },
            VanillaEntry {
                name: "lukewarm_ocean",
                offset: 72719,
                len: 3262,
            },
            VanillaEntry {
                name: "lush_caves",
                offset: 75981,
                len: 2706,
            },
            VanillaEntry {
                name: "mangrove_swamp",
                offset: 78687,
                len: 3066,
            },
            VanillaEntry {
                name: "meadow",
                offset: 81753,
                len: 2682,
            },
            VanillaEntry {
                name: "mushroom_fields",
                offset: 84435,
                len: 1939,
            },
            VanillaEntry {
                name: "nether_wastes",
                offset: 86374,
                len: 1753,
            },
            VanillaEntry {
                name: "ocean",
                offset: 88127,
                len: 3071,
            },
            VanillaEntry {
                name: "old_growth_birch_forest",
                offset: 91198,
                len: 2880,
            },
            VanillaEntry {
                name: "old_growth_pine_taiga",
                offset: 94078,
                len: 3204,
            },
            VanillaEntry {
                name: "old_growth_spruce_taiga",
                offset: 97282,
                len: 3206,
            },
            VanillaEntry {
                name: "pale_garden",
                offset: 100488,
                len: 2649,
            },
            VanillaEntry {
                name: "plains",
                offset: 103137,
                len: 2939,
            },
            VanillaEntry {
                name: "river",
                offset: 106076,
                len: 2933,
            },
            VanillaEntry {
                name: "savanna",
                offset: 109009,
                len: 3027,
            },
            VanillaEntry {
                name: "savanna_plateau",
                offset: 112036,
                len: 3162,
            },
            VanillaEntry {
                name: "small_end_islands",
                offset: 115198,
                len: 415,
            },
            VanillaEntry {
                name: "snowy_beach",
                offset: 115613,
                len: 2385,
            },
            VanillaEntry {
                name: "snowy_plains",
                offset: 117998,
                len: 2730,
            },
            VanillaEntry {
                name: "snowy_slopes",
                offset: 120728,
                len: 2579,
            },
            VanillaEntry {
                name: "snowy_taiga",
                offset: 123307,
                len: 2933,
            },
            VanillaEntry {
                name: "soul_sand_valley",
                offset: 126240,
                len: 1915,
            },
            VanillaEntry {
                name: "sparse_jungle",
                offset: 128155,
                len: 2993,
            },
            VanillaEntry {
                name: "stony_peaks",
                offset: 131148,
                len: 2342,
            },
            VanillaEntry {
                name: "stony_shore",
                offset: 133490,
                len: 2385,
            },
            VanillaEntry {
                name: "sulfur_caves",
                offset: 135875,
                len: 2548,
            },
            VanillaEntry {
                name: "sunflower_plains",
                offset: 138423,
                len: 2944,
            },
            VanillaEntry {
                name: "swamp",
                offset: 141367,
                len: 3448,
            },
            VanillaEntry {
                name: "taiga",
                offset: 144815,
                len: 2935,
            },
            VanillaEntry {
                name: "the_end",
                offset: 147750,
                len: 478,
            },
            VanillaEntry {
                name: "the_void",
                offset: 148228,
                len: 445,
            },
            VanillaEntry {
                name: "warm_ocean",
                offset: 148673,
                len: 3230,
            },
            VanillaEntry {
                name: "warped_forest",
                offset: 151903,
                len: 1683,
            },
            VanillaEntry {
                name: "windswept_forest",
                offset: 153586,
                len: 2826,
            },
            VanillaEntry {
                name: "windswept_gravelly_hills",
                offset: 156412,
                len: 2825,
            },
            VanillaEntry {
                name: "windswept_hills",
                offset: 159237,
                len: 2825,
            },
            VanillaEntry {
                name: "windswept_savanna",
                offset: 162062,
                len: 3011,
            },
            VanillaEntry {
                name: "wooded_badlands",
                offset: 165073,
                len: 3182,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:chat_type",
        entries: &[
            VanillaEntry {
                name: "chat",
                offset: 168255,
                len: 169,
            },
            VanillaEntry {
                name: "emote_command",
                offset: 168424,
                len: 163,
            },
            VanillaEntry {
                name: "msg_command_incoming",
                offset: 168587,
                len: 221,
            },
            VanillaEntry {
                name: "msg_command_outgoing",
                offset: 168808,
                len: 221,
            },
            VanillaEntry {
                name: "say_command",
                offset: 169029,
                len: 177,
            },
            VanillaEntry {
                name: "team_msg_command_incoming",
                offset: 169206,
                len: 182,
            },
            VanillaEntry {
                name: "team_msg_command_outgoing",
                offset: 169388,
                len: 182,
            },
            VanillaEntry {
                name: "raw",
                offset: 169570,
                len: 137,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:trim_pattern",
        entries: &[
            VanillaEntry {
                name: "bolt",
                offset: 169707,
                len: 94,
            },
            VanillaEntry {
                name: "coast",
                offset: 169801,
                len: 96,
            },
            VanillaEntry {
                name: "dune",
                offset: 169897,
                len: 94,
            },
            VanillaEntry {
                name: "eye",
                offset: 169991,
                len: 92,
            },
            VanillaEntry {
                name: "flow",
                offset: 170083,
                len: 94,
            },
            VanillaEntry {
                name: "host",
                offset: 170177,
                len: 94,
            },
            VanillaEntry {
                name: "raiser",
                offset: 170271,
                len: 98,
            },
            VanillaEntry {
                name: "rib",
                offset: 170369,
                len: 92,
            },
            VanillaEntry {
                name: "sentry",
                offset: 170461,
                len: 98,
            },
            VanillaEntry {
                name: "shaper",
                offset: 170559,
                len: 98,
            },
            VanillaEntry {
                name: "silence",
                offset: 170657,
                len: 100,
            },
            VanillaEntry {
                name: "snout",
                offset: 170757,
                len: 96,
            },
            VanillaEntry {
                name: "spire",
                offset: 170853,
                len: 96,
            },
            VanillaEntry {
                name: "tide",
                offset: 170949,
                len: 94,
            },
            VanillaEntry {
                name: "vex",
                offset: 171043,
                len: 92,
            },
            VanillaEntry {
                name: "ward",
                offset: 171135,
                len: 94,
            },
            VanillaEntry {
                name: "wayfinder",
                offset: 171229,
                len: 104,
            },
            VanillaEntry {
                name: "wild",
                offset: 171333,
                len: 94,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:trim_material",
        entries: &[
            VanillaEntry {
                name: "amethyst",
                offset: 171427,
                len: 103,
            },
            VanillaEntry {
                name: "copper",
                offset: 171530,
                len: 158,
            },
            VanillaEntry {
                name: "diamond",
                offset: 171688,
                len: 162,
            },
            VanillaEntry {
                name: "emerald",
                offset: 171850,
                len: 101,
            },
            VanillaEntry {
                name: "gold",
                offset: 171951,
                len: 150,
            },
            VanillaEntry {
                name: "iron",
                offset: 172101,
                len: 150,
            },
            VanillaEntry {
                name: "lapis",
                offset: 172251,
                len: 97,
            },
            VanillaEntry {
                name: "netherite",
                offset: 172348,
                len: 170,
            },
            VanillaEntry {
                name: "quartz",
                offset: 172518,
                len: 99,
            },
            VanillaEntry {
                name: "redstone",
                offset: 172617,
                len: 103,
            },
            VanillaEntry {
                name: "resin",
                offset: 172720,
                len: 97,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:wolf_variant",
        entries: &[
            VanillaEntry {
                name: "ashen",
                offset: 172817,
                len: 421,
            },
            VanillaEntry {
                name: "black",
                offset: 173238,
                len: 431,
            },
            VanillaEntry {
                name: "chestnut",
                offset: 173669,
                len: 451,
            },
            VanillaEntry {
                name: "pale",
                offset: 174120,
                len: 316,
            },
            VanillaEntry {
                name: "rusty",
                offset: 174436,
                len: 420,
            },
            VanillaEntry {
                name: "snowy",
                offset: 174856,
                len: 415,
            },
            VanillaEntry {
                name: "spotted",
                offset: 175271,
                len: 433,
            },
            VanillaEntry {
                name: "striped",
                offset: 175704,
                len: 434,
            },
            VanillaEntry {
                name: "woods",
                offset: 176138,
                len: 416,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:wolf_sound_variant",
        entries: &[
            VanillaEntry {
                name: "angry",
                offset: 176554,
                len: 702,
            },
            VanillaEntry {
                name: "big",
                offset: 177256,
                len: 690,
            },
            VanillaEntry {
                name: "classic",
                offset: 177946,
                len: 666,
            },
            VanillaEntry {
                name: "cute",
                offset: 178612,
                len: 696,
            },
            VanillaEntry {
                name: "grumpy",
                offset: 179308,
                len: 708,
            },
            VanillaEntry {
                name: "puglin",
                offset: 180016,
                len: 708,
            },
            VanillaEntry {
                name: "sad",
                offset: 180724,
                len: 690,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:pig_variant",
        entries: &[
            VanillaEntry {
                name: "cold",
                offset: 181414,
                len: 241,
            },
            VanillaEntry {
                name: "temperate",
                offset: 181655,
                len: 146,
            },
            VanillaEntry {
                name: "warm",
                offset: 181801,
                len: 227,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:pig_sound_variant",
        entries: &[
            VanillaEntry {
                name: "big",
                offset: 182028,
                len: 486,
            },
            VanillaEntry {
                name: "classic",
                offset: 182514,
                len: 470,
            },
            VanillaEntry {
                name: "mini",
                offset: 182984,
                len: 490,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:frog_variant",
        entries: &[
            VanillaEntry {
                name: "cold",
                offset: 183474,
                len: 170,
            },
            VanillaEntry {
                name: "temperate",
                offset: 183644,
                len: 91,
            },
            VanillaEntry {
                name: "warm",
                offset: 183735,
                len: 170,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:cat_variant",
        entries: &[
            VanillaEntry {
                name: "all_black",
                offset: 183905,
                len: 318,
            },
            VanillaEntry {
                name: "black",
                offset: 184223,
                len: 138,
            },
            VanillaEntry {
                name: "british_shorthair",
                offset: 184361,
                len: 162,
            },
            VanillaEntry {
                name: "calico",
                offset: 184523,
                len: 140,
            },
            VanillaEntry {
                name: "jellie",
                offset: 184663,
                len: 140,
            },
            VanillaEntry {
                name: "persian",
                offset: 184803,
                len: 142,
            },
            VanillaEntry {
                name: "ragdoll",
                offset: 184945,
                len: 142,
            },
            VanillaEntry {
                name: "red",
                offset: 185087,
                len: 134,
            },
            VanillaEntry {
                name: "siamese",
                offset: 185221,
                len: 142,
            },
            VanillaEntry {
                name: "tabby",
                offset: 185363,
                len: 138,
            },
            VanillaEntry {
                name: "white",
                offset: 185501,
                len: 138,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:cat_sound_variant",
        entries: &[
            VanillaEntry {
                name: "classic",
                offset: 185639,
                len: 890,
            },
            VanillaEntry {
                name: "royal",
                offset: 186529,
                len: 944,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:cow_variant",
        entries: &[
            VanillaEntry {
                name: "cold",
                offset: 187473,
                len: 241,
            },
            VanillaEntry {
                name: "temperate",
                offset: 187714,
                len: 146,
            },
            VanillaEntry {
                name: "warm",
                offset: 187860,
                len: 241,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:cow_sound_variant",
        entries: &[
            VanillaEntry {
                name: "classic",
                offset: 188101,
                len: 170,
            },
            VanillaEntry {
                name: "moody",
                offset: 188271,
                len: 194,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:chicken_variant",
        entries: &[
            VanillaEntry {
                name: "cold",
                offset: 188465,
                len: 257,
            },
            VanillaEntry {
                name: "temperate",
                offset: 188722,
                len: 162,
            },
            VanillaEntry {
                name: "warm",
                offset: 188884,
                len: 243,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:chicken_sound_variant",
        entries: &[
            VanillaEntry {
                name: "classic",
                offset: 189127,
                len: 421,
            },
            VanillaEntry {
                name: "picky",
                offset: 189548,
                len: 439,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:zombie_nautilus_variant",
        entries: &[
            VanillaEntry {
                name: "temperate",
                offset: 189987,
                len: 96,
            },
            VanillaEntry {
                name: "warm",
                offset: 190083,
                len: 211,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:painting_variant",
        entries: &[
            VanillaEntry {
                name: "alban",
                offset: 190294,
                len: 193,
            },
            VanillaEntry {
                name: "aztec",
                offset: 190487,
                len: 193,
            },
            VanillaEntry {
                name: "aztec2",
                offset: 190680,
                len: 196,
            },
            VanillaEntry {
                name: "backyard",
                offset: 190876,
                len: 202,
            },
            VanillaEntry {
                name: "baroque",
                offset: 191078,
                len: 199,
            },
            VanillaEntry {
                name: "bomb",
                offset: 191277,
                len: 190,
            },
            VanillaEntry {
                name: "bouquet",
                offset: 191467,
                len: 199,
            },
            VanillaEntry {
                name: "burning_skull",
                offset: 191666,
                len: 217,
            },
            VanillaEntry {
                name: "bust",
                offset: 191883,
                len: 190,
            },
            VanillaEntry {
                name: "cavebird",
                offset: 192073,
                len: 202,
            },
            VanillaEntry {
                name: "changing",
                offset: 192275,
                len: 202,
            },
            VanillaEntry {
                name: "cotan",
                offset: 192477,
                len: 193,
            },
            VanillaEntry {
                name: "courbet",
                offset: 192670,
                len: 199,
            },
            VanillaEntry {
                name: "creebet",
                offset: 192869,
                len: 199,
            },
            VanillaEntry {
                name: "dennis",
                offset: 193068,
                len: 196,
            },
            VanillaEntry {
                name: "donkey_kong",
                offset: 193264,
                len: 211,
            },
            VanillaEntry {
                name: "earth",
                offset: 193475,
                len: 124,
            },
            VanillaEntry {
                name: "endboss",
                offset: 193599,
                len: 199,
            },
            VanillaEntry {
                name: "fern",
                offset: 193798,
                len: 190,
            },
            VanillaEntry {
                name: "fighters",
                offset: 193988,
                len: 202,
            },
            VanillaEntry {
                name: "finding",
                offset: 194190,
                len: 199,
            },
            VanillaEntry {
                name: "fire",
                offset: 194389,
                len: 122,
            },
            VanillaEntry {
                name: "graham",
                offset: 194511,
                len: 196,
            },
            VanillaEntry {
                name: "humble",
                offset: 194707,
                len: 196,
            },
            VanillaEntry {
                name: "kebab",
                offset: 194903,
                len: 193,
            },
            VanillaEntry {
                name: "lowmist",
                offset: 195096,
                len: 199,
            },
            VanillaEntry {
                name: "match",
                offset: 195295,
                len: 193,
            },
            VanillaEntry {
                name: "meditative",
                offset: 195488,
                len: 208,
            },
            VanillaEntry {
                name: "orb",
                offset: 195696,
                len: 187,
            },
            VanillaEntry {
                name: "owlemons",
                offset: 195883,
                len: 202,
            },
            VanillaEntry {
                name: "passage",
                offset: 196085,
                len: 199,
            },
            VanillaEntry {
                name: "pigscene",
                offset: 196284,
                len: 202,
            },
            VanillaEntry {
                name: "plant",
                offset: 196486,
                len: 193,
            },
            VanillaEntry {
                name: "pointer",
                offset: 196679,
                len: 199,
            },
            VanillaEntry {
                name: "pond",
                offset: 196878,
                len: 190,
            },
            VanillaEntry {
                name: "pool",
                offset: 197068,
                len: 190,
            },
            VanillaEntry {
                name: "prairie_ride",
                offset: 197258,
                len: 214,
            },
            VanillaEntry {
                name: "sea",
                offset: 197472,
                len: 187,
            },
            VanillaEntry {
                name: "skeleton",
                offset: 197659,
                len: 202,
            },
            VanillaEntry {
                name: "skull_and_roses",
                offset: 197861,
                len: 223,
            },
            VanillaEntry {
                name: "stage",
                offset: 198084,
                len: 193,
            },
            VanillaEntry {
                name: "sunflowers",
                offset: 198277,
                len: 208,
            },
            VanillaEntry {
                name: "sunset",
                offset: 198485,
                len: 196,
            },
            VanillaEntry {
                name: "tides",
                offset: 198681,
                len: 193,
            },
            VanillaEntry {
                name: "unpacked",
                offset: 198874,
                len: 202,
            },
            VanillaEntry {
                name: "void",
                offset: 199076,
                len: 190,
            },
            VanillaEntry {
                name: "wanderer",
                offset: 199266,
                len: 202,
            },
            VanillaEntry {
                name: "wasteland",
                offset: 199468,
                len: 205,
            },
            VanillaEntry {
                name: "water",
                offset: 199673,
                len: 124,
            },
            VanillaEntry {
                name: "wind",
                offset: 199797,
                len: 122,
            },
            VanillaEntry {
                name: "wither",
                offset: 199919,
                len: 126,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:dimension_type",
        entries: &[
            VanillaEntry {
                name: "overworld",
                offset: 200045,
                len: 1180,
            },
            VanillaEntry {
                name: "overworld_caves",
                offset: 201225,
                len: 1180,
            },
            VanillaEntry {
                name: "the_end",
                offset: 202405,
                len: 985,
            },
            VanillaEntry {
                name: "the_nether",
                offset: 203390,
                len: 1048,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:damage_type",
        entries: &[
            VanillaEntry {
                name: "arrow",
                offset: 204438,
                len: 87,
            },
            VanillaEntry {
                name: "bad_respawn_point",
                offset: 204525,
                len: 117,
            },
            VanillaEntry {
                name: "cactus",
                offset: 204642,
                len: 88,
            },
            VanillaEntry {
                name: "campfire",
                offset: 204730,
                len: 107,
            },
            VanillaEntry {
                name: "cramming",
                offset: 204837,
                len: 90,
            },
            VanillaEntry {
                name: "dragon_breath",
                offset: 204927,
                len: 94,
            },
            VanillaEntry {
                name: "drown",
                offset: 205021,
                len: 107,
            },
            VanillaEntry {
                name: "dry_out",
                offset: 205128,
                len: 88,
            },
            VanillaEntry {
                name: "ender_pearl",
                offset: 205216,
                len: 122,
            },
            VanillaEntry {
                name: "explosion",
                offset: 205338,
                len: 65,
            },
            VanillaEntry {
                name: "fall",
                offset: 205403,
                len: 122,
            },
            VanillaEntry {
                name: "falling_anvil",
                offset: 205525,
                len: 87,
            },
            VanillaEntry {
                name: "falling_block",
                offset: 205612,
                len: 94,
            },
            VanillaEntry {
                name: "falling_stalactite",
                offset: 205706,
                len: 99,
            },
            VanillaEntry {
                name: "fireball",
                offset: 205805,
                len: 109,
            },
            VanillaEntry {
                name: "fireworks",
                offset: 205914,
                len: 91,
            },
            VanillaEntry {
                name: "fly_into_wall",
                offset: 206005,
                len: 93,
            },
            VanillaEntry {
                name: "freeze",
                offset: 206098,
                len: 108,
            },
            VanillaEntry {
                name: "generic",
                offset: 206206,
                len: 89,
            },
            VanillaEntry {
                name: "generic_kill",
                offset: 206295,
                len: 93,
            },
            VanillaEntry {
                name: "hot_floor",
                offset: 206388,
                len: 109,
            },
            VanillaEntry {
                name: "in_fire",
                offset: 206497,
                len: 107,
            },
            VanillaEntry {
                name: "in_wall",
                offset: 206604,
                len: 88,
            },
            VanillaEntry {
                name: "indirect_magic",
                offset: 206692,
                len: 95,
            },
            VanillaEntry {
                name: "lava",
                offset: 206787,
                len: 105,
            },
            VanillaEntry {
                name: "lightning_bolt",
                offset: 206892,
                len: 95,
            },
            VanillaEntry {
                name: "mace_smash",
                offset: 206987,
                len: 92,
            },
            VanillaEntry {
                name: "magic",
                offset: 207079,
                len: 87,
            },
            VanillaEntry {
                name: "mob_attack",
                offset: 207166,
                len: 85,
            },
            VanillaEntry {
                name: "mob_attack_no_aggro",
                offset: 207251,
                len: 85,
            },
            VanillaEntry {
                name: "mob_projectile",
                offset: 207336,
                len: 85,
            },
            VanillaEntry {
                name: "on_fire",
                offset: 207421,
                len: 107,
            },
            VanillaEntry {
                name: "out_of_world",
                offset: 207528,
                len: 92,
            },
            VanillaEntry {
                name: "outside_border",
                offset: 207620,
                len: 95,
            },
            VanillaEntry {
                name: "player_attack",
                offset: 207715,
                len: 88,
            },
            VanillaEntry {
                name: "player_explosion",
                offset: 207803,
                len: 72,
            },
            VanillaEntry {
                name: "sonic_boom",
                offset: 207875,
                len: 66,
            },
            VanillaEntry {
                name: "spear",
                offset: 207941,
                len: 87,
            },
            VanillaEntry {
                name: "spit",
                offset: 208028,
                len: 85,
            },
            VanillaEntry {
                name: "stalagmite",
                offset: 208113,
                len: 92,
            },
            VanillaEntry {
                name: "starve",
                offset: 208205,
                len: 88,
            },
            VanillaEntry {
                name: "sting",
                offset: 208293,
                len: 87,
            },
            VanillaEntry {
                name: "sulfur_cube_hot",
                offset: 208380,
                len: 114,
            },
            VanillaEntry {
                name: "sweet_berry_bush",
                offset: 208494,
                len: 114,
            },
            VanillaEntry {
                name: "thorns",
                offset: 208608,
                len: 106,
            },
            VanillaEntry {
                name: "thrown",
                offset: 208714,
                len: 88,
            },
            VanillaEntry {
                name: "trident",
                offset: 208802,
                len: 89,
            },
            VanillaEntry {
                name: "unattributed_fireball",
                offset: 208891,
                len: 107,
            },
            VanillaEntry {
                name: "wind_charge",
                offset: 208998,
                len: 85,
            },
            VanillaEntry {
                name: "wither",
                offset: 209083,
                len: 88,
            },
            VanillaEntry {
                name: "wither_skull",
                offset: 209171,
                len: 93,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:jukebox_song",
        entries: &[
            VanillaEntry {
                name: "11",
                offset: 209264,
                len: 147,
            },
            VanillaEntry {
                name: "13",
                offset: 209411,
                len: 147,
            },
            VanillaEntry {
                name: "5",
                offset: 209558,
                len: 145,
            },
            VanillaEntry {
                name: "blocks",
                offset: 209703,
                len: 155,
            },
            VanillaEntry {
                name: "bounce",
                offset: 209858,
                len: 155,
            },
            VanillaEntry {
                name: "cat",
                offset: 210013,
                len: 149,
            },
            VanillaEntry {
                name: "chirp",
                offset: 210162,
                len: 153,
            },
            VanillaEntry {
                name: "creator",
                offset: 210315,
                len: 157,
            },
            VanillaEntry {
                name: "creator_music_box",
                offset: 210472,
                len: 177,
            },
            VanillaEntry {
                name: "far",
                offset: 210649,
                len: 149,
            },
            VanillaEntry {
                name: "lava_chicken",
                offset: 210798,
                len: 167,
            },
            VanillaEntry {
                name: "mall",
                offset: 210965,
                len: 151,
            },
            VanillaEntry {
                name: "mellohi",
                offset: 211116,
                len: 157,
            },
            VanillaEntry {
                name: "otherside",
                offset: 211273,
                len: 161,
            },
            VanillaEntry {
                name: "pigstep",
                offset: 211434,
                len: 157,
            },
            VanillaEntry {
                name: "precipice",
                offset: 211591,
                len: 161,
            },
            VanillaEntry {
                name: "relic",
                offset: 211752,
                len: 153,
            },
            VanillaEntry {
                name: "stal",
                offset: 211905,
                len: 151,
            },
            VanillaEntry {
                name: "strad",
                offset: 212056,
                len: 153,
            },
            VanillaEntry {
                name: "tears",
                offset: 212209,
                len: 153,
            },
            VanillaEntry {
                name: "wait",
                offset: 212362,
                len: 151,
            },
            VanillaEntry {
                name: "ward",
                offset: 212513,
                len: 151,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:banner_pattern",
        entries: &[
            VanillaEntry {
                name: "base",
                offset: 212664,
                len: 76,
            },
            VanillaEntry {
                name: "border",
                offset: 212740,
                len: 80,
            },
            VanillaEntry {
                name: "bricks",
                offset: 212820,
                len: 80,
            },
            VanillaEntry {
                name: "circle",
                offset: 212900,
                len: 80,
            },
            VanillaEntry {
                name: "creeper",
                offset: 212980,
                len: 82,
            },
            VanillaEntry {
                name: "cross",
                offset: 213062,
                len: 78,
            },
            VanillaEntry {
                name: "curly_border",
                offset: 213140,
                len: 92,
            },
            VanillaEntry {
                name: "diagonal_left",
                offset: 213232,
                len: 94,
            },
            VanillaEntry {
                name: "diagonal_right",
                offset: 213326,
                len: 96,
            },
            VanillaEntry {
                name: "diagonal_up_left",
                offset: 213422,
                len: 100,
            },
            VanillaEntry {
                name: "diagonal_up_right",
                offset: 213522,
                len: 102,
            },
            VanillaEntry {
                name: "flow",
                offset: 213624,
                len: 76,
            },
            VanillaEntry {
                name: "flower",
                offset: 213700,
                len: 80,
            },
            VanillaEntry {
                name: "globe",
                offset: 213780,
                len: 78,
            },
            VanillaEntry {
                name: "gradient",
                offset: 213858,
                len: 84,
            },
            VanillaEntry {
                name: "gradient_up",
                offset: 213942,
                len: 90,
            },
            VanillaEntry {
                name: "guster",
                offset: 214032,
                len: 80,
            },
            VanillaEntry {
                name: "half_horizontal",
                offset: 214112,
                len: 98,
            },
            VanillaEntry {
                name: "half_horizontal_bottom",
                offset: 214210,
                len: 112,
            },
            VanillaEntry {
                name: "half_vertical",
                offset: 214322,
                len: 94,
            },
            VanillaEntry {
                name: "half_vertical_right",
                offset: 214416,
                len: 106,
            },
            VanillaEntry {
                name: "mojang",
                offset: 214522,
                len: 80,
            },
            VanillaEntry {
                name: "piglin",
                offset: 214602,
                len: 80,
            },
            VanillaEntry {
                name: "rhombus",
                offset: 214682,
                len: 82,
            },
            VanillaEntry {
                name: "skull",
                offset: 214764,
                len: 78,
            },
            VanillaEntry {
                name: "small_stripes",
                offset: 214842,
                len: 94,
            },
            VanillaEntry {
                name: "square_bottom_left",
                offset: 214936,
                len: 104,
            },
            VanillaEntry {
                name: "square_bottom_right",
                offset: 215040,
                len: 106,
            },
            VanillaEntry {
                name: "square_top_left",
                offset: 215146,
                len: 98,
            },
            VanillaEntry {
                name: "square_top_right",
                offset: 215244,
                len: 100,
            },
            VanillaEntry {
                name: "straight_cross",
                offset: 215344,
                len: 96,
            },
            VanillaEntry {
                name: "stripe_bottom",
                offset: 215440,
                len: 94,
            },
            VanillaEntry {
                name: "stripe_center",
                offset: 215534,
                len: 94,
            },
            VanillaEntry {
                name: "stripe_downleft",
                offset: 215628,
                len: 98,
            },
            VanillaEntry {
                name: "stripe_downright",
                offset: 215726,
                len: 100,
            },
            VanillaEntry {
                name: "stripe_left",
                offset: 215826,
                len: 90,
            },
            VanillaEntry {
                name: "stripe_middle",
                offset: 215916,
                len: 94,
            },
            VanillaEntry {
                name: "stripe_right",
                offset: 216010,
                len: 92,
            },
            VanillaEntry {
                name: "stripe_top",
                offset: 216102,
                len: 88,
            },
            VanillaEntry {
                name: "triangle_bottom",
                offset: 216190,
                len: 98,
            },
            VanillaEntry {
                name: "triangle_top",
                offset: 216288,
                len: 92,
            },
            VanillaEntry {
                name: "triangles_bottom",
                offset: 216380,
                len: 100,
            },
            VanillaEntry {
                name: "triangles_top",
                offset: 216480,
                len: 94,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:instrument",
        entries: &[
            VanillaEntry {
                name: "admire_goat_horn",
                offset: 216574,
                len: 155,
            },
            VanillaEntry {
                name: "call_goat_horn",
                offset: 216729,
                len: 153,
            },
            VanillaEntry {
                name: "dream_goat_horn",
                offset: 216882,
                len: 154,
            },
            VanillaEntry {
                name: "feel_goat_horn",
                offset: 217036,
                len: 153,
            },
            VanillaEntry {
                name: "ponder_goat_horn",
                offset: 217189,
                len: 155,
            },
            VanillaEntry {
                name: "seek_goat_horn",
                offset: 217344,
                len: 153,
            },
            VanillaEntry {
                name: "sing_goat_horn",
                offset: 217497,
                len: 153,
            },
            VanillaEntry {
                name: "yearn_goat_horn",
                offset: 217650,
                len: 154,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:enchantment",
        entries: &[
            VanillaEntry {
                name: "aqua_affinity",
                offset: 217804,
                len: 530,
            },
            VanillaEntry {
                name: "bane_of_arthropods",
                offset: 218334,
                len: 1273,
            },
            VanillaEntry {
                name: "binding_curse",
                offset: 219607,
                len: 332,
            },
            VanillaEntry {
                name: "blast_protection",
                offset: 219939,
                len: 911,
            },
            VanillaEntry {
                name: "breach",
                offset: 220850,
                len: 488,
            },
            VanillaEntry {
                name: "channeling",
                offset: 221338,
                len: 1514,
            },
            VanillaEntry {
                name: "density",
                offset: 222852,
                len: 499,
            },
            VanillaEntry {
                name: "depth_strider",
                offset: 223351,
                len: 570,
            },
            VanillaEntry {
                name: "efficiency",
                offset: 223921,
                len: 485,
            },
            VanillaEntry {
                name: "feather_falling",
                offset: 224406,
                len: 629,
            },
            VanillaEntry {
                name: "fire_aspect",
                offset: 225035,
                len: 633,
            },
            VanillaEntry {
                name: "fire_protection",
                offset: 225668,
                len: 940,
            },
            VanillaEntry {
                name: "flame",
                offset: 226608,
                len: 377,
            },
            VanillaEntry {
                name: "fortune",
                offset: 226985,
                len: 334,
            },
            VanillaEntry {
                name: "frost_walker",
                offset: 227319,
                len: 1594,
            },
            VanillaEntry {
                name: "impaling",
                offset: 228913,
                len: 623,
            },
            VanillaEntry {
                name: "infinity",
                offset: 229536,
                len: 498,
            },
            VanillaEntry {
                name: "knockback",
                offset: 230034,
                len: 440,
            },
            VanillaEntry {
                name: "looting",
                offset: 230474,
                len: 597,
            },
            VanillaEntry {
                name: "loyalty",
                offset: 231071,
                len: 451,
            },
            VanillaEntry {
                name: "luck_of_the_sea",
                offset: 231522,
                len: 450,
            },
            VanillaEntry {
                name: "lunge",
                offset: 231972,
                len: 1769,
            },
            VanillaEntry {
                name: "lure",
                offset: 233741,
                len: 443,
            },
            VanillaEntry {
                name: "mending",
                offset: 234184,
                len: 377,
            },
            VanillaEntry {
                name: "multishot",
                offset: 234561,
                len: 643,
            },
            VanillaEntry {
                name: "piercing",
                offset: 235204,
                len: 496,
            },
            VanillaEntry {
                name: "power",
                offset: 235700,
                len: 563,
            },
            VanillaEntry {
                name: "projectile_protection",
                offset: 236263,
                len: 684,
            },
            VanillaEntry {
                name: "protection",
                offset: 236947,
                len: 630,
            },
            VanillaEntry {
                name: "punch",
                offset: 237577,
                len: 566,
            },
            VanillaEntry {
                name: "quick_charge",
                offset: 238143,
                len: 762,
            },
            VanillaEntry {
                name: "respiration",
                offset: 238905,
                len: 505,
            },
            VanillaEntry {
                name: "riptide",
                offset: 239410,
                len: 616,
            },
            VanillaEntry {
                name: "sharpness",
                offset: 240026,
                len: 539,
            },
            VanillaEntry {
                name: "silk_touch",
                offset: 240565,
                len: 431,
            },
            VanillaEntry {
                name: "smite",
                offset: 240996,
                len: 669,
            },
            VanillaEntry {
                name: "soul_speed",
                offset: 241665,
                len: 3372,
            },
            VanillaEntry {
                name: "sweeping_edge",
                offset: 245037,
                len: 647,
            },
            VanillaEntry {
                name: "swift_sneak",
                offset: 245684,
                len: 506,
            },
            VanillaEntry {
                name: "thorns",
                offset: 246190,
                len: 800,
            },
            VanillaEntry {
                name: "unbreaking",
                offset: 246990,
                len: 1072,
            },
            VanillaEntry {
                name: "vanishing_curse",
                offset: 248062,
                len: 333,
            },
            VanillaEntry {
                name: "wind_burst",
                offset: 248395,
                len: 1016,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:timeline",
        entries: &[
            VanillaEntry {
                name: "day",
                offset: 249411,
                len: 4347,
            },
            VanillaEntry {
                name: "early_game",
                offset: 253758,
                len: 166,
            },
            VanillaEntry {
                name: "moon",
                offset: 253924,
                len: 728,
            },
            VanillaEntry {
                name: "villager_schedule",
                offset: 254652,
                len: 549,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:dialog",
        entries: &[
            VanillaEntry {
                name: "custom_options",
                offset: 255201,
                len: 267,
            },
            VanillaEntry {
                name: "quick_actions",
                offset: 255468,
                len: 256,
            },
            VanillaEntry {
                name: "server_links",
                offset: 255724,
                len: 219,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:world_clock",
        entries: &[
            VanillaEntry {
                name: "overworld",
                offset: 255943,
                len: 2,
            },
            VanillaEntry {
                name: "the_end",
                offset: 255945,
                len: 2,
            },
        ],
    },
    VanillaRegistry {
        id: "minecraft:test_environment",
        entries: &[VanillaEntry {
            name: "default",
            offset: 255947,
            len: 46,
        }],
    },
    VanillaRegistry {
        id: "minecraft:test_instance",
        entries: &[VanillaEntry {
            name: "always_pass",
            offset: 255993,
            len: 171,
        }],
    },
    VanillaRegistry {
        id: "minecraft:sulfur_cube_archetype",
        entries: &[
            VanillaEntry {
                name: "bouncy",
                offset: 256164,
                len: 1034,
            },
            VanillaEntry {
                name: "explosive",
                offset: 257198,
                len: 1109,
            },
            VanillaEntry {
                name: "fast_flat",
                offset: 258307,
                len: 1047,
            },
            VanillaEntry {
                name: "fast_sliding",
                offset: 259354,
                len: 1071,
            },
            VanillaEntry {
                name: "high_resistance",
                offset: 260425,
                len: 1095,
            },
            VanillaEntry {
                name: "hot",
                offset: 261520,
                len: 1109,
            },
            VanillaEntry {
                name: "light",
                offset: 262629,
                len: 1026,
            },
            VanillaEntry {
                name: "regular",
                offset: 263655,
                len: 1042,
            },
            VanillaEntry {
                name: "slow_bouncy",
                offset: 264697,
                len: 1063,
            },
            VanillaEntry {
                name: "slow_flat",
                offset: 265760,
                len: 1047,
            },
            VanillaEntry {
                name: "slow_sliding",
                offset: 266807,
                len: 1071,
            },
            VanillaEntry {
                name: "sticky",
                offset: 267878,
                len: 1023,
            },
        ],
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    fn entry_index(registry: &str, entry: &str) -> i32 {
        let registry = VANILLA_REGISTRIES
            .iter()
            .find(|value| value.id == registry)
            .unwrap();
        registry
            .entries
            .iter()
            .position(|value| value.name == entry)
            .unwrap() as i32
    }

    #[test]
    fn pumpkin_26_2_registry_blob_is_complete() {
        assert_eq!(VANILLA_REGISTRIES.len(), 29);
        assert_eq!(
            VANILLA_REGISTRIES
                .iter()
                .map(|value| value.entries.len())
                .sum::<usize>(),
            398
        );
        for registry in VANILLA_REGISTRIES {
            for entry in registry.entries {
                let data = REGISTRY_BLOB
                    .get(entry.offset..entry.offset + entry.len)
                    .unwrap();
                assert_eq!(data.first(), Some(&0x0a), "{}.{}", registry.id, entry.name);
            }
        }
    }

    #[test]
    fn generated_wire_indices_match_registry_order() {
        assert_eq!(
            BIOME_PLAINS,
            entry_index("minecraft:worldgen/biome", "plains")
        );
        assert_eq!(
            DIMENSION_TYPE_OVERWORLD,
            entry_index("minecraft:dimension_type", "overworld")
        );
        assert_eq!(
            DAMAGE_TYPE_PLAYER_ATTACK,
            entry_index("minecraft:damage_type", "player_attack")
        );
        assert_eq!(
            WORLD_CLOCK_OVERWORLD,
            entry_index("minecraft:world_clock", "overworld")
        );
    }
}
