// Generated by tools/pumpkin-import/import_tags.py. Do not edit.
// Pumpkin beb6947dfc21a1a781523bf207a3c2740f4928f9, Minecraft 26.2.

#[cfg(test)]
pub struct TagRegistrySummary {
    pub id: &'static str,
    pub tag_count: usize,
}

pub const TAG_DATA: &[u8] = include_bytes!("vanilla_tags.bin");
#[cfg(test)]
pub const TAG_COUNT: usize = 1207;
#[cfg(test)]
pub const TAG_ENTRY_COUNT: usize = 11693;

#[cfg(test)]
pub static TAG_REGISTRIES: &[TagRegistrySummary] = &[
    TagRegistrySummary {
        id: "minecraft:banner_pattern",
        tag_count: 11,
    },
    TagRegistrySummary {
        id: "minecraft:block",
        tag_count: 392,
    },
    TagRegistrySummary {
        id: "minecraft:cat_variant",
        tag_count: 0,
    },
    TagRegistrySummary {
        id: "minecraft:damage_type",
        tag_count: 34,
    },
    TagRegistrySummary {
        id: "minecraft:dialog",
        tag_count: 2,
    },
    TagRegistrySummary {
        id: "minecraft:dimension_type",
        tag_count: 0,
    },
    TagRegistrySummary {
        id: "minecraft:enchantment",
        tag_count: 29,
    },
    TagRegistrySummary {
        id: "minecraft:entity_type",
        tag_count: 54,
    },
    TagRegistrySummary {
        id: "minecraft:fluid",
        tag_count: 18,
    },
    TagRegistrySummary {
        id: "minecraft:game_event",
        tag_count: 5,
    },
    TagRegistrySummary {
        id: "minecraft:instrument",
        tag_count: 3,
    },
    TagRegistrySummary {
        id: "minecraft:item",
        tag_count: 488,
    },
    TagRegistrySummary {
        id: "minecraft:painting_variant",
        tag_count: 1,
    },
    TagRegistrySummary {
        id: "minecraft:point_of_interest_type",
        tag_count: 3,
    },
    TagRegistrySummary {
        id: "minecraft:potion",
        tag_count: 2,
    },
    TagRegistrySummary {
        id: "minecraft:timeline",
        tag_count: 4,
    },
    TagRegistrySummary {
        id: "minecraft:worldgen/biome",
        tag_count: 161,
    },
];

#[cfg(test)]
mod tests {
    use super::*;
    use net_ws::Decoder;

    #[test]
    fn pumpkin_26_2_tag_blob_is_complete() {
        let mut decoder = Decoder::new(TAG_DATA);
        assert_eq!(decoder.varint(), Ok(TAG_REGISTRIES.len() as i32));
        let mut tag_count = 0;
        let mut entry_count = 0;
        let mut required = [false; 3];
        for expected in TAG_REGISTRIES {
            assert_eq!(decoder.string().as_deref(), Ok(expected.id));
            let count = decoder.varint().unwrap() as usize;
            assert_eq!(count, expected.tag_count);
            tag_count += count;
            for _ in 0..count {
                let name = decoder.string().unwrap();
                required[0] |= name == "minecraft:infiniburn_overworld";
                required[1] |= name == "minecraft:enchantable/armor";
                required[2] |= name == "minecraft:sulfur_cube_archetype/regular";
                let values = decoder.varint().unwrap() as usize;
                entry_count += values;
                for _ in 0..values {
                    assert!(decoder.varint().unwrap() >= 0);
                }
            }
        }
        assert_eq!(tag_count, TAG_COUNT);
        assert_eq!(entry_count, TAG_ENTRY_COUNT);
        assert!(required.into_iter().all(|value| value));
        assert!(decoder.is_empty());
    }
}
