pub struct VanillaEntry {
    pub name: &'static str,
    pub offset: usize,
    pub len: usize,
}

pub struct VanillaRegistry {
    pub id: &'static str,
    pub entries: &'static [VanillaEntry],
}

pub const REGISTRY_BLOB: &[u8] = include_bytes!("vanilla_registries.bin");

pub static VANILLA_REGISTRIES: &[VanillaRegistry] = &[
    VanillaRegistry {
        id: "minecraft:worldgen/biome",
        entries: &[
            VanillaEntry { name: "badlands", offset: 0, len: 450 },
            VanillaEntry { name: "bamboo_jungle", offset: 450, len: 417 },
            VanillaEntry { name: "basalt_deltas", offset: 867, len: 647 },
            VanillaEntry { name: "beach", offset: 1514, len: 276 },
            VanillaEntry { name: "birch_forest", offset: 1790, len: 410 },
            VanillaEntry { name: "cherry_grove", offset: 2200, len: 454 },
            VanillaEntry { name: "cold_ocean", offset: 2654, len: 276 },
            VanillaEntry { name: "crimson_forest", offset: 2930, len: 655 },
            VanillaEntry { name: "dark_forest", offset: 3585, len: 446 },
            VanillaEntry { name: "deep_cold_ocean", offset: 4031, len: 276 },
            VanillaEntry { name: "deep_dark", offset: 4307, len: 413 },
            VanillaEntry { name: "deep_frozen_ocean", offset: 4720, len: 307 },
            VanillaEntry { name: "deep_lukewarm_ocean", offset: 5027, len: 276 },
            VanillaEntry { name: "deep_ocean", offset: 5303, len: 276 },
            VanillaEntry { name: "desert", offset: 5579, len: 410 },
            VanillaEntry { name: "dripstone_caves", offset: 5989, len: 419 },
            VanillaEntry { name: "end_barrens", offset: 6408, len: 276 },
            VanillaEntry { name: "end_highlands", offset: 6684, len: 276 },
            VanillaEntry { name: "end_midlands", offset: 6960, len: 276 },
            VanillaEntry { name: "eroded_badlands", offset: 7236, len: 450 },
            VanillaEntry { name: "flower_forest", offset: 7686, len: 417 },
            VanillaEntry { name: "forest", offset: 8103, len: 410 },
            VanillaEntry { name: "frozen_ocean", offset: 8513, len: 307 },
            VanillaEntry { name: "frozen_peaks", offset: 8820, len: 416 },
            VanillaEntry { name: "frozen_river", offset: 9236, len: 276 },
            VanillaEntry { name: "grove", offset: 9512, len: 409 },
            VanillaEntry { name: "ice_spikes", offset: 9921, len: 276 },
            VanillaEntry { name: "jagged_peaks", offset: 10197, len: 416 },
            VanillaEntry { name: "jungle", offset: 10613, len: 410 },
            VanillaEntry { name: "lukewarm_ocean", offset: 11023, len: 276 },
            VanillaEntry { name: "lush_caves", offset: 11299, len: 414 },
            VanillaEntry { name: "mangrove_swamp", offset: 11713, len: 459 },
            VanillaEntry { name: "meadow", offset: 12172, len: 410 },
            VanillaEntry { name: "mushroom_fields", offset: 12582, len: 276 },
            VanillaEntry { name: "nether_wastes", offset: 12858, len: 574 },
            VanillaEntry { name: "ocean", offset: 13432, len: 276 },
            VanillaEntry { name: "old_growth_birch_forest", offset: 13708, len: 410 },
            VanillaEntry { name: "old_growth_pine_taiga", offset: 14118, len: 420 },
            VanillaEntry { name: "old_growth_spruce_taiga", offset: 14538, len: 420 },
            VanillaEntry { name: "pale_garden", offset: 14958, len: 327 },
            VanillaEntry { name: "plains", offset: 15285, len: 276 },
            VanillaEntry { name: "river", offset: 15561, len: 276 },
            VanillaEntry { name: "savanna", offset: 15837, len: 276 },
            VanillaEntry { name: "savanna_plateau", offset: 16113, len: 276 },
            VanillaEntry { name: "small_end_islands", offset: 16389, len: 276 },
            VanillaEntry { name: "snowy_beach", offset: 16665, len: 276 },
            VanillaEntry { name: "snowy_plains", offset: 16941, len: 276 },
            VanillaEntry { name: "snowy_slopes", offset: 17217, len: 416 },
            VanillaEntry { name: "snowy_taiga", offset: 17633, len: 276 },
            VanillaEntry { name: "soul_sand_valley", offset: 17909, len: 653 },
            VanillaEntry { name: "sparse_jungle", offset: 18562, len: 417 },
            VanillaEntry { name: "stony_peaks", offset: 18979, len: 415 },
            VanillaEntry { name: "stony_shore", offset: 19394, len: 276 },
            VanillaEntry { name: "sunflower_plains", offset: 19670, len: 276 },
            VanillaEntry { name: "swamp", offset: 19946, len: 459 },
            VanillaEntry { name: "taiga", offset: 20405, len: 276 },
            VanillaEntry { name: "the_end", offset: 20681, len: 276 },
            VanillaEntry { name: "the_void", offset: 20957, len: 276 },
            VanillaEntry { name: "warm_ocean", offset: 21233, len: 276 },
            VanillaEntry { name: "warped_forest", offset: 21509, len: 650 },
            VanillaEntry { name: "windswept_forest", offset: 22159, len: 276 },
            VanillaEntry { name: "windswept_gravelly_hills", offset: 22435, len: 276 },
            VanillaEntry { name: "windswept_hills", offset: 22711, len: 276 },
            VanillaEntry { name: "windswept_savanna", offset: 22987, len: 276 },
            VanillaEntry { name: "wooded_badlands", offset: 23263, len: 450 },
        ],
    },
    VanillaRegistry {
        id: "minecraft:chat_type",
        entries: &[
            VanillaEntry { name: "chat", offset: 23713, len: 169 },
            VanillaEntry { name: "emote_command", offset: 23882, len: 163 },
            VanillaEntry { name: "msg_command_incoming", offset: 24045, len: 221 },
            VanillaEntry { name: "msg_command_outgoing", offset: 24266, len: 221 },
            VanillaEntry { name: "say_command", offset: 24487, len: 177 },
            VanillaEntry { name: "team_msg_command_incoming", offset: 24664, len: 182 },
            VanillaEntry { name: "team_msg_command_outgoing", offset: 24846, len: 182 },
            VanillaEntry { name: "raw", offset: 25028, len: 137 },
        ],
    },
    VanillaRegistry {
        id: "minecraft:trim_pattern",
        entries: &[
            VanillaEntry { name: "bolt", offset: 25165, len: 155 },
            VanillaEntry { name: "coast", offset: 25320, len: 158 },
            VanillaEntry { name: "dune", offset: 25478, len: 155 },
            VanillaEntry { name: "eye", offset: 25633, len: 152 },
            VanillaEntry { name: "flow", offset: 25785, len: 155 },
            VanillaEntry { name: "host", offset: 25940, len: 155 },
            VanillaEntry { name: "raiser", offset: 26095, len: 161 },
            VanillaEntry { name: "rib", offset: 26256, len: 152 },
            VanillaEntry { name: "sentry", offset: 26408, len: 161 },
            VanillaEntry { name: "shaper", offset: 26569, len: 161 },
            VanillaEntry { name: "silence", offset: 26730, len: 164 },
            VanillaEntry { name: "snout", offset: 26894, len: 158 },
            VanillaEntry { name: "spire", offset: 27052, len: 158 },
            VanillaEntry { name: "tide", offset: 27210, len: 155 },
            VanillaEntry { name: "vex", offset: 27365, len: 152 },
            VanillaEntry { name: "ward", offset: 27517, len: 155 },
            VanillaEntry { name: "wayfinder", offset: 27672, len: 170 },
            VanillaEntry { name: "wild", offset: 27842, len: 155 },
        ],
    },
    VanillaRegistry {
        id: "minecraft:trim_material",
        entries: &[
            VanillaEntry { name: "amethyst", offset: 27997, len: 142 },
            VanillaEntry { name: "copper", offset: 28139, len: 136 },
            VanillaEntry { name: "diamond", offset: 28275, len: 194 },
            VanillaEntry { name: "emerald", offset: 28469, len: 133 },
            VanillaEntry { name: "gold", offset: 28602, len: 185 },
            VanillaEntry { name: "iron", offset: 28787, len: 185 },
            VanillaEntry { name: "lapis", offset: 28972, len: 134 },
            VanillaEntry { name: "netherite", offset: 29106, len: 210 },
            VanillaEntry { name: "quartz", offset: 29316, len: 130 },
            VanillaEntry { name: "redstone", offset: 29446, len: 136 },
            VanillaEntry { name: "resin", offset: 29582, len: 133 },
        ],
    },
    VanillaRegistry {
        id: "minecraft:wolf_variant",
        entries: &[
            VanillaEntry { name: "ashen", offset: 29715, len: 193 },
            VanillaEntry { name: "black", offset: 29908, len: 203 },
            VanillaEntry { name: "chestnut", offset: 30111, len: 214 },
            VanillaEntry { name: "pale", offset: 30325, len: 169 },
            VanillaEntry { name: "rusty", offset: 30494, len: 192 },
            VanillaEntry { name: "snowy", offset: 30686, len: 187 },
            VanillaEntry { name: "spotted", offset: 30873, len: 199 },
            VanillaEntry { name: "striped", offset: 31072, len: 200 },
            VanillaEntry { name: "woods", offset: 31272, len: 188 },
        ],
    },
    VanillaRegistry {
        id: "minecraft:painting_variant",
        entries: &[
            VanillaEntry { name: "alban", offset: 31460, len: 193 },
            VanillaEntry { name: "aztec", offset: 31653, len: 193 },
            VanillaEntry { name: "aztec2", offset: 31846, len: 196 },
            VanillaEntry { name: "backyard", offset: 32042, len: 202 },
            VanillaEntry { name: "baroque", offset: 32244, len: 199 },
            VanillaEntry { name: "bomb", offset: 32443, len: 190 },
            VanillaEntry { name: "bouquet", offset: 32633, len: 199 },
            VanillaEntry { name: "burning_skull", offset: 32832, len: 217 },
            VanillaEntry { name: "bust", offset: 33049, len: 190 },
            VanillaEntry { name: "cavebird", offset: 33239, len: 202 },
            VanillaEntry { name: "changing", offset: 33441, len: 202 },
            VanillaEntry { name: "cotan", offset: 33643, len: 193 },
            VanillaEntry { name: "courbet", offset: 33836, len: 199 },
            VanillaEntry { name: "creebet", offset: 34035, len: 199 },
            VanillaEntry { name: "donkey_kong", offset: 34234, len: 211 },
            VanillaEntry { name: "earth", offset: 34445, len: 124 },
            VanillaEntry { name: "endboss", offset: 34569, len: 199 },
            VanillaEntry { name: "fern", offset: 34768, len: 190 },
            VanillaEntry { name: "fighters", offset: 34958, len: 202 },
            VanillaEntry { name: "finding", offset: 35160, len: 199 },
            VanillaEntry { name: "fire", offset: 35359, len: 122 },
            VanillaEntry { name: "graham", offset: 35481, len: 196 },
            VanillaEntry { name: "humble", offset: 35677, len: 196 },
            VanillaEntry { name: "kebab", offset: 35873, len: 193 },
            VanillaEntry { name: "lowmist", offset: 36066, len: 199 },
            VanillaEntry { name: "match", offset: 36265, len: 193 },
            VanillaEntry { name: "meditative", offset: 36458, len: 208 },
            VanillaEntry { name: "orb", offset: 36666, len: 187 },
            VanillaEntry { name: "owlemons", offset: 36853, len: 202 },
            VanillaEntry { name: "passage", offset: 37055, len: 199 },
            VanillaEntry { name: "pigscene", offset: 37254, len: 202 },
            VanillaEntry { name: "plant", offset: 37456, len: 193 },
            VanillaEntry { name: "pointer", offset: 37649, len: 199 },
            VanillaEntry { name: "pond", offset: 37848, len: 190 },
            VanillaEntry { name: "pool", offset: 38038, len: 190 },
            VanillaEntry { name: "prairie_ride", offset: 38228, len: 214 },
            VanillaEntry { name: "sea", offset: 38442, len: 187 },
            VanillaEntry { name: "skeleton", offset: 38629, len: 202 },
            VanillaEntry { name: "skull_and_roses", offset: 38831, len: 223 },
            VanillaEntry { name: "stage", offset: 39054, len: 193 },
            VanillaEntry { name: "sunflowers", offset: 39247, len: 208 },
            VanillaEntry { name: "sunset", offset: 39455, len: 196 },
            VanillaEntry { name: "tides", offset: 39651, len: 193 },
            VanillaEntry { name: "unpacked", offset: 39844, len: 202 },
            VanillaEntry { name: "void", offset: 40046, len: 190 },
            VanillaEntry { name: "wanderer", offset: 40236, len: 202 },
            VanillaEntry { name: "wasteland", offset: 40438, len: 205 },
            VanillaEntry { name: "water", offset: 40643, len: 124 },
            VanillaEntry { name: "wind", offset: 40767, len: 122 },
            VanillaEntry { name: "wither", offset: 40889, len: 126 },
        ],
    },
    VanillaRegistry {
        id: "minecraft:dimension_type",
        entries: &[
            VanillaEntry { name: "overworld", offset: 41015, len: 429 },
            VanillaEntry { name: "overworld_caves", offset: 41444, len: 429 },
            VanillaEntry { name: "the_end", offset: 41873, len: 438 },
            VanillaEntry { name: "the_nether", offset: 42311, len: 381 },
        ],
    },
    VanillaRegistry {
        id: "minecraft:damage_type",
        entries: &[
            VanillaEntry { name: "arrow", offset: 42692, len: 87 },
            VanillaEntry { name: "bad_respawn_point", offset: 42779, len: 117 },
            VanillaEntry { name: "cactus", offset: 42896, len: 88 },
            VanillaEntry { name: "campfire", offset: 42984, len: 107 },
            VanillaEntry { name: "cramming", offset: 43091, len: 90 },
            VanillaEntry { name: "dragon_breath", offset: 43181, len: 94 },
            VanillaEntry { name: "drown", offset: 43275, len: 107 },
            VanillaEntry { name: "dry_out", offset: 43382, len: 88 },
            VanillaEntry { name: "ender_pearl", offset: 43470, len: 122 },
            VanillaEntry { name: "explosion", offset: 43592, len: 65 },
            VanillaEntry { name: "fall", offset: 43657, len: 122 },
            VanillaEntry { name: "falling_anvil", offset: 43779, len: 87 },
            VanillaEntry { name: "falling_block", offset: 43866, len: 94 },
            VanillaEntry { name: "falling_stalactite", offset: 43960, len: 99 },
            VanillaEntry { name: "fireball", offset: 44059, len: 109 },
            VanillaEntry { name: "fireworks", offset: 44168, len: 91 },
            VanillaEntry { name: "fly_into_wall", offset: 44259, len: 93 },
            VanillaEntry { name: "freeze", offset: 44352, len: 108 },
            VanillaEntry { name: "generic", offset: 44460, len: 89 },
            VanillaEntry { name: "generic_kill", offset: 44549, len: 93 },
            VanillaEntry { name: "hot_floor", offset: 44642, len: 109 },
            VanillaEntry { name: "in_fire", offset: 44751, len: 107 },
            VanillaEntry { name: "in_wall", offset: 44858, len: 88 },
            VanillaEntry { name: "indirect_magic", offset: 44946, len: 95 },
            VanillaEntry { name: "lava", offset: 45041, len: 105 },
            VanillaEntry { name: "lightning_bolt", offset: 45146, len: 95 },
            VanillaEntry { name: "mace_smash", offset: 45241, len: 92 },
            VanillaEntry { name: "magic", offset: 45333, len: 87 },
            VanillaEntry { name: "mob_attack", offset: 45420, len: 85 },
            VanillaEntry { name: "mob_attack_no_aggro", offset: 45505, len: 85 },
            VanillaEntry { name: "mob_projectile", offset: 45590, len: 85 },
            VanillaEntry { name: "on_fire", offset: 45675, len: 107 },
            VanillaEntry { name: "out_of_world", offset: 45782, len: 92 },
            VanillaEntry { name: "outside_border", offset: 45874, len: 95 },
            VanillaEntry { name: "player_attack", offset: 45969, len: 88 },
            VanillaEntry { name: "player_explosion", offset: 46057, len: 72 },
            VanillaEntry { name: "sonic_boom", offset: 46129, len: 66 },
            VanillaEntry { name: "spit", offset: 46195, len: 85 },
            VanillaEntry { name: "stalagmite", offset: 46280, len: 92 },
            VanillaEntry { name: "starve", offset: 46372, len: 88 },
            VanillaEntry { name: "sting", offset: 46460, len: 87 },
            VanillaEntry { name: "sweet_berry_bush", offset: 46547, len: 114 },
            VanillaEntry { name: "thorns", offset: 46661, len: 106 },
            VanillaEntry { name: "thrown", offset: 46767, len: 88 },
            VanillaEntry { name: "trident", offset: 46855, len: 89 },
            VanillaEntry { name: "unattributed_fireball", offset: 46944, len: 107 },
            VanillaEntry { name: "wind_charge", offset: 47051, len: 85 },
            VanillaEntry { name: "wither", offset: 47136, len: 88 },
            VanillaEntry { name: "wither_skull", offset: 47224, len: 93 },
        ],
    },
    VanillaRegistry {
        id: "minecraft:jukebox_song",
        entries: &[
            VanillaEntry { name: "11", offset: 47317, len: 147 },
            VanillaEntry { name: "13", offset: 47464, len: 147 },
            VanillaEntry { name: "5", offset: 47611, len: 145 },
            VanillaEntry { name: "blocks", offset: 47756, len: 155 },
            VanillaEntry { name: "cat", offset: 47911, len: 149 },
            VanillaEntry { name: "chirp", offset: 48060, len: 153 },
            VanillaEntry { name: "creator", offset: 48213, len: 157 },
            VanillaEntry { name: "creator_music_box", offset: 48370, len: 177 },
            VanillaEntry { name: "far", offset: 48547, len: 149 },
            VanillaEntry { name: "mall", offset: 48696, len: 151 },
            VanillaEntry { name: "mellohi", offset: 48847, len: 157 },
            VanillaEntry { name: "otherside", offset: 49004, len: 161 },
            VanillaEntry { name: "pigstep", offset: 49165, len: 157 },
            VanillaEntry { name: "precipice", offset: 49322, len: 161 },
            VanillaEntry { name: "relic", offset: 49483, len: 153 },
            VanillaEntry { name: "stal", offset: 49636, len: 151 },
            VanillaEntry { name: "strad", offset: 49787, len: 153 },
            VanillaEntry { name: "wait", offset: 49940, len: 151 },
            VanillaEntry { name: "ward", offset: 50091, len: 151 },
        ],
    },
    VanillaRegistry {
        id: "minecraft:banner_pattern",
        entries: &[
            VanillaEntry { name: "base", offset: 50242, len: 76 },
            VanillaEntry { name: "border", offset: 50318, len: 80 },
            VanillaEntry { name: "bricks", offset: 50398, len: 80 },
            VanillaEntry { name: "circle", offset: 50478, len: 80 },
            VanillaEntry { name: "creeper", offset: 50558, len: 82 },
            VanillaEntry { name: "cross", offset: 50640, len: 78 },
            VanillaEntry { name: "curly_border", offset: 50718, len: 92 },
            VanillaEntry { name: "diagonal_left", offset: 50810, len: 94 },
            VanillaEntry { name: "diagonal_right", offset: 50904, len: 96 },
            VanillaEntry { name: "diagonal_up_left", offset: 51000, len: 100 },
            VanillaEntry { name: "diagonal_up_right", offset: 51100, len: 102 },
            VanillaEntry { name: "flow", offset: 51202, len: 76 },
            VanillaEntry { name: "flower", offset: 51278, len: 80 },
            VanillaEntry { name: "globe", offset: 51358, len: 78 },
            VanillaEntry { name: "gradient", offset: 51436, len: 84 },
            VanillaEntry { name: "gradient_up", offset: 51520, len: 90 },
            VanillaEntry { name: "guster", offset: 51610, len: 80 },
            VanillaEntry { name: "half_horizontal", offset: 51690, len: 98 },
            VanillaEntry { name: "half_horizontal_bottom", offset: 51788, len: 112 },
            VanillaEntry { name: "half_vertical", offset: 51900, len: 94 },
            VanillaEntry { name: "half_vertical_right", offset: 51994, len: 106 },
            VanillaEntry { name: "mojang", offset: 52100, len: 80 },
            VanillaEntry { name: "piglin", offset: 52180, len: 80 },
            VanillaEntry { name: "rhombus", offset: 52260, len: 82 },
            VanillaEntry { name: "skull", offset: 52342, len: 78 },
            VanillaEntry { name: "small_stripes", offset: 52420, len: 94 },
            VanillaEntry { name: "square_bottom_left", offset: 52514, len: 104 },
            VanillaEntry { name: "square_bottom_right", offset: 52618, len: 106 },
            VanillaEntry { name: "square_top_left", offset: 52724, len: 98 },
            VanillaEntry { name: "square_top_right", offset: 52822, len: 100 },
            VanillaEntry { name: "straight_cross", offset: 52922, len: 96 },
            VanillaEntry { name: "stripe_bottom", offset: 53018, len: 94 },
            VanillaEntry { name: "stripe_center", offset: 53112, len: 94 },
            VanillaEntry { name: "stripe_downleft", offset: 53206, len: 98 },
            VanillaEntry { name: "stripe_downright", offset: 53304, len: 100 },
            VanillaEntry { name: "stripe_left", offset: 53404, len: 90 },
            VanillaEntry { name: "stripe_middle", offset: 53494, len: 94 },
            VanillaEntry { name: "stripe_right", offset: 53588, len: 92 },
            VanillaEntry { name: "stripe_top", offset: 53680, len: 88 },
            VanillaEntry { name: "triangle_bottom", offset: 53768, len: 98 },
            VanillaEntry { name: "triangle_top", offset: 53866, len: 92 },
            VanillaEntry { name: "triangles_bottom", offset: 53958, len: 100 },
            VanillaEntry { name: "triangles_top", offset: 54058, len: 94 },
        ],
    },
    VanillaRegistry {
        id: "minecraft:instrument",
        entries: &[
            VanillaEntry { name: "admire_goat_horn", offset: 54152, len: 155 },
            VanillaEntry { name: "call_goat_horn", offset: 54307, len: 153 },
            VanillaEntry { name: "dream_goat_horn", offset: 54460, len: 154 },
            VanillaEntry { name: "feel_goat_horn", offset: 54614, len: 153 },
            VanillaEntry { name: "ponder_goat_horn", offset: 54767, len: 155 },
            VanillaEntry { name: "seek_goat_horn", offset: 54922, len: 153 },
            VanillaEntry { name: "sing_goat_horn", offset: 55075, len: 153 },
            VanillaEntry { name: "yearn_goat_horn", offset: 55228, len: 154 },
        ],
    },
    VanillaRegistry {
        id: "minecraft:enchantment",
        entries: &[
            VanillaEntry { name: "aqua_affinity", offset: 55382, len: 530 },
            VanillaEntry { name: "bane_of_arthropods", offset: 55912, len: 1232 },
            VanillaEntry { name: "binding_curse", offset: 57144, len: 332 },
            VanillaEntry { name: "blast_protection", offset: 57476, len: 911 },
            VanillaEntry { name: "breach", offset: 58387, len: 488 },
            VanillaEntry { name: "channeling", offset: 58875, len: 1503 },
            VanillaEntry { name: "density", offset: 60378, len: 499 },
            VanillaEntry { name: "depth_strider", offset: 60877, len: 570 },
            VanillaEntry { name: "efficiency", offset: 61447, len: 485 },
            VanillaEntry { name: "feather_falling", offset: 61932, len: 629 },
            VanillaEntry { name: "fire_aspect", offset: 62561, len: 626 },
            VanillaEntry { name: "fire_protection", offset: 63187, len: 940 },
            VanillaEntry { name: "flame", offset: 64127, len: 377 },
            VanillaEntry { name: "fortune", offset: 64504, len: 334 },
            VanillaEntry { name: "frost_walker", offset: 64838, len: 1574 },
            VanillaEntry { name: "impaling", offset: 66412, len: 606 },
            VanillaEntry { name: "infinity", offset: 67018, len: 498 },
            VanillaEntry { name: "knockback", offset: 67516, len: 433 },
            VanillaEntry { name: "looting", offset: 67949, len: 573 },
            VanillaEntry { name: "loyalty", offset: 68522, len: 451 },
            VanillaEntry { name: "luck_of_the_sea", offset: 68973, len: 450 },
            VanillaEntry { name: "lure", offset: 69423, len: 443 },
            VanillaEntry { name: "mending", offset: 69866, len: 377 },
            VanillaEntry { name: "multishot", offset: 70243, len: 643 },
            VanillaEntry { name: "piercing", offset: 70886, len: 496 },
            VanillaEntry { name: "power", offset: 71382, len: 546 },
            VanillaEntry { name: "projectile_protection", offset: 71928, len: 684 },
            VanillaEntry { name: "protection", offset: 72612, len: 630 },
            VanillaEntry { name: "punch", offset: 73242, len: 549 },
            VanillaEntry { name: "quick_charge", offset: 73791, len: 762 },
            VanillaEntry { name: "respiration", offset: 74553, len: 505 },
            VanillaEntry { name: "riptide", offset: 75058, len: 616 },
            VanillaEntry { name: "sharpness", offset: 75674, len: 532 },
            VanillaEntry { name: "silk_touch", offset: 76206, len: 431 },
            VanillaEntry { name: "smite", offset: 76637, len: 645 },
            VanillaEntry { name: "soul_speed", offset: 77282, len: 3212 },
            VanillaEntry { name: "sweeping_edge", offset: 80494, len: 644 },
            VanillaEntry { name: "swift_sneak", offset: 81138, len: 506 },
            VanillaEntry { name: "thorns", offset: 81644, len: 800 },
            VanillaEntry { name: "unbreaking", offset: 82444, len: 1072 },
            VanillaEntry { name: "vanishing_curse", offset: 83516, len: 333 },
            VanillaEntry { name: "wind_burst", offset: 83849, len: 996 },
        ],
    },
];
